### ISSUE TITLE
SNOM devices fails to load XML phonebook

### ISSUE THREAD

**Issue by shamrockDE** [Massi-X/freepbx-phonemiddleware#14]
Again: Thanks a million for this new version. I've installed it in my FreePBX and i got it working!
I found two problems,  this is the issue for the second one.

~~**Is your feature request related to a problem? Please describe.**
No, because the XML-Output-File uses correct XML-syntax. The problem is, that SNOM-Phones do not accept this syntax for empty numbers.~~

~~**Describe the solution you'd like**
The syntax for empty numbers in the XML-output from `carddavmiddleware` is
`<Mobile/>`
which is correct and allowed.~~

~~But the SNOM-telephone requires the following syntax for empty entries:
`<Mobile></Mobile>`~~

~~**Describe alternatives you've considered**
I've downloaded the XML-Output to a file and replaced
`<Office/>` with `<Office></Office>`
`<Mobile/>` with `<Mobile></Mobile>`
With this change i am able to load the phonebook to my SNOM-phones, without this change i get errors while loading.~~

~~**Additional context**
Again: Great work. Anything else in the XML-output for SNOM-Phones is correct now and with this two search and replace commands i was able to load the phonebook.~~

See update https://github.com/Massi-X/freepbx-phonemiddleware/issues/14#issuecomment-1491040648
The output is correct, something else is preventing the XML from loading.

**Comment by Massi-X** [comment]
Thank you, thought I had included this in the latest version. I will release a fix for this tomorrow!

**Comment by Massi-X** [comment]
Hi @shamrockDE sadly I can't reproduce your issue because after checking the fix was already included in v.2.0.0.

Could you check that the file is the right one? Please share with me the first two lines of the XML file (they should be something like
```
<!-- cached: 1677845731 -->
<!-- md5: 2dad36b56f6d0ae86485fc69ab4e384d -->
```
) to make sure this is the correct file, in fact phonemiddleware did not generate the md5 line and we can decode the cached time to understand if this is the updated file.

Also what is the path of the file your editing?

**Comment by shamrockDE** [comment]
In the SNOM-configuration i can use an url for the global phonebook.
I want to set the link `https://freepbx/carddavmiddleware/carddavtoxml.php` (freepbx is the servername of my freepbx-installation) which i get within the module administration under `XML phonebook for your device`.

If i open this link in my webbrowser (in my case firefox), i receive the xml-file (reduced to one entry, name and number anonymized):
```xml
<IPPhoneDirectory>
<DirectoryEntry>
<Name>xxxx yyyy</Name>
<Telephone>+49721nnnnn</Telephone>
<Office/>
<Mobile/>
</DirectoryEntry>
</IPPhoneDirectory>
```

I save this file directly from my bowser to disk. If i try to load it manually as global phonebook into my SNOM-device, the upload is not successful. After changing the two entries for `Office` and `Mobile` as explained above, the upload is successful and i can see the names and numbers on my SNOM-phones.

I can't see cached or md5 in the XML-file at this point. The only line which i can see in the "page source" before the `<IPPhoneDirectory>` is
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by Massi-X** [comment]
Could you confirm that the phonebook get correctly updated by inserting a new phone number and waiting (or forcing) for the cache to refresh?

Which freepbx system are you on?

**Comment by shamrockDE** [comment]
> Could you confirm that the phonebook get correctly updated by inserting a new phone number and waiting (or forcing) for the cache to refresh?

I can see any change on entries in my Nextcloud-Addressbook on my freebpx. I can see them in Superfecta and also in the XML-phonebook for my devices. So the short answer ist 'Yes'.

> Which freepbx system are you on?

FreePBX 16.0.39 (from FreePBX Dashboard)
Asterisk 18.16.0 (from Asterisk-Information Report inside FreePBX)
PHP Version 7.4.16 (From PHP-Info-Report inside FreePBX)

**Comment by Massi-X** [comment]
Could you please upload, run this module and send me the output (Menu in Applications->Test, a screenshot is fine)
[test.tar.gz](https://github.com/Massi-X/freepbx-phonemiddleware/files/11071949/test.tar.gz)

**Comment by shamrockDE** [comment]
I am on a business trip this week and not at home. I will install and run the module when i am back home, thursday or friday.

**Comment by shamrockDE** [comment]
Hi,
this the Output of the module "test":

Test 1:
<?xml version="1.0" encoding="UTF-8"?> <tag1></tag1><tag2></tag2><tag3></tag3><tag4> </tag4><tag5>something</tag5><tag6/><tag7></tag7>

**Comment by shamrockDE** [comment]
Hi,
this is the output of the module Test:

```xml
Test 1:
<?xml version="1.0" encoding="UTF-8"?> <tag1></tag1><tag2></tag2><tag3></tag3><tag4> </tag4><tag5>something</tag5><tag6/><tag7><!--comm--></tag7> 
```

**Comment by Massi-X** [comment]
OK so this tells that everything works fine. I found out that what is the root cause of what you see.
The browser shows a parsed (and modified) version of the xml file, if you follow [this](https://support.mozilla.org/it/questions/873324#answer-243976) procedure you will see that the file is indeed given back with the right format.
You can use Chrome to save the file (ctrl+S/cmd+S) and you will see the correct file (sadly Firefox modify the file it downloads, you should report this bug to Firefox developers).

All that said now the question is: if the file is correct (and it is) there is probably something else that is preventing the file from loading on SNOM devices. You should try the following:
1. Download the file with Chrome
2. Without touching it, try to give it to SNOM and see if it works
3. If not, start with little modifications to find out what is causing the problem

Also now it comes to my mind that you were using https on the server (said it in issue #13), maybe it fails for that?

Let me know!

**Comment by shamrockDE** [comment]
I loaded the xml-output as global-phonebook to my snom box and compared the entries. There was only one problem with the name of an entry. I configured the CNAM as combination with `title`, `full card name` and `organization name`. When the organization name contains a minus `-`, the name of this entry is not visible in the phone book after loading. But this name is correct in the XML-file, so this must be a snom problem.

I haven't found any more difference or problem, so the output is equivalent now to the snom specifications.

Thanks a million for your help and for this new version of the module, which is great.

I close this issue now.

**Comment by Massi-X** [comment]
Thank you, anyway this entry prevents the whole file from loading right? (Or that entry only?)
Maybe I have to do some encoding but I don't really know as I don't have such devices

**Comment by shamrockDE** [comment]
No this entry doesn't prevent loading. The whole file is fully loaded including the affected entry.

The name of the affected entry (xml-field `<name></name>`) consists of the full name and the organization. If the organization in the name field contains a "-", the entry appears on the phones, but the name is empty. If I replace the "-" in the organization in the XML file entry with a blank  and reload the file, the entry is displayed on the phones with the correct name.

It's definitely not an error in the XML file, but in the global address book in SNOM, either when loading or when displaying.
