### ISSUE TITLE
Source for CallerID Lookup?

### ISSUE THREAD

**Issue by shamrockDE** [Massi-X/freepbx-phonemiddleware#15]
This is more a question than a feature request

**Is your feature request related to a problem? Please describe.**
The old version (phoneMiddleware) could also be used as `CallerID Lookup Source`.

Is this also possible with `carddavmiddleware`?
If not, do you have planned to implement this function in the future?

**Comment by Massi-X** [comment]
Hi I don't know, why you need it?
I drop support for CallerID Lookup Source because superfecta is more configurable and should fullfil all the use cases.

Anyway the only thing preventing cidlookup from working now is the need of a POST request (and that only.support GET).

**Comment by shamrockDE** [comment]
I took a closer look at both functions and you are right. Superfecta is the more powerful function and there is no need for CallerID Lookup Source.
Thanks for your answer and as i wrote, it was just a question. I close thise issue.
