### ISSUE TITLE
Unable to load phonebook because of attribute "clearlight" in XML-element "IPPhoneDirectory"

### ISSUE THREAD

**Issue by shamrockDE** [Massi-X/freepbx-phonemiddleware#3]
**Describe the bug**
Part of the first XML-element "IPPhoneDirectory" is the attribute "clearlight":
<IPPhoneDirectory clearlight="1">
I found no way to get rid of these attribute

**To Reproduce**
I saved the XML-ouput from this module to a file
1. If i load this file to my snom-Phone (M300) i can't see any entry in the global telephonebook on my handhelds
2. If i delete this attribute manually from the XML-element and load the same file again to my snom-Phone, all Entries are shown in the global telephonebook

**Expected behavior**
An option in the administration of the module could help to include this attribute or not

**IP Phone:**
 - Device: snom M300 with M25 handheld
 - Version: Version 530 Branch 02

**Comment by Massi-X** [comment]
Ok after some researching (it is very difficult to find information on this phones) seems like this attribute was only used on some Snow phones but never really necessary. I will simply remove it, wait for an update shortly

**Comment by shamrockDE** [comment]
Thank you for the quick implementation, the output is correct now.
