### ISSUE TITLE
Customize the displayed names

### ISSUE THREAD

**Issue by zerrac** [Massi-X/freepbx-phonemiddleware#4]
Hello ! First, thanks you for this plugin that solve the lack of carddav support in every softphone i tried :)

I wanted to display the company name of my contacts during a call.

I made my dirty little modification in my corner and it works:
```
329c340,351
<                                                       $foundCNAM = $vCard->fn[0]; //this is the name
---
>                                                       if (count($vCard->org)>0) {
>                                                               $services = ' (' . $vCard->org[0]['Name'] ;
> 
>                                                               if (! empty($vCard->org[0]['Unit1'])) {
>                                                                       $services .= ' - '.$vCard->org[0]['Unit1'];
>                                                               }
> 
>                                                               $services .= ')';
> 
>                                                       }
> 
>                                                       $foundCNAM = $vCard->fn[0] . $services; //this is the name
```

I think it may be useful to be able to customize the displayed name from freepbx admin with some templating for instance.

**Comment by Massi-X** [comment]
Hi thank you for your submission! I'm happy to see that this helps someone 😊
About your request: Yes it can be implemented with some further testing, the thing I don't understand is what you mean when you say "some templating"

**Comment by zerrac** [comment]
I imagine something like an input in module admin where you could use some pre defined tags that will be replaced by vcard values during number processing.

For my need it may have been: 

Custom name display : "<contact_name> (<contact_org_name> - <contact_org_unit1>)"

I guess a str_replace would then do the trick if every contacts have the relevant fields set.

I also did a brief research on PHP templating engines and found out twig could be used to add conditional logic.

I am not sure its a good idea to bring twig template complexity in user interface though 😁 


Le 29 mars 2022 21:12:28 GMT+02:00, Massi-X ***@***.***> a écrit :

**Comment by Massi-X** [comment]
Good point, Will implement it in one of the next release. Think it will take me some weeks because I have little time now but will surely do.

**Comment by Massi-X** [comment]
Hi, your feature has been implemented in v1.0.6. I'll leave this issue open because the logic needs to be implemented for XML phonebook too, but for now you can update and see everything working on incoming calls!

**Comment by zerrac** [comment]
Amazing, thank you !

**Comment by Massi-X** [comment]
Completed implementation for phonebook too in v1.2.0, so closing the issue. Will probably make some change in the future in the way this is displayed (parenthesis and such) but for now everything seems good enough.
