### ISSUE TITLE
Leading "+" in phonenumbers isn't replaced with "00"

### ISSUE THREAD

**Issue by shamrockDE** [Massi-X/freepbx-phonemiddleware#7]
**Describe the bug**
The function "arrayTelWalk" in file helpers/phoneMiddleware.php has following comment:
//Then replace + with 00 for better compatibility with asterisk
I was wandering, because my phonenumbers have still the leading "+"

i changed the following line (#470) from
$object = preg_replace('/[^0-9]\*/', '00', $object);
to
$object = preg_replace('/^\+/', '00', $object);
and now, the "+" is replaced with "00" in my output.

**Comment by Massi-X** [comment]
Thank you it was a copy-paste error. Fix in the next version

**Comment by Massi-X** [comment]
Fixed in v1.0.6
